if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias dc='docker-compose'

alias dl='~/.dotfiles/network/transmission/start.sh'

alias ga='git add'
alias gcam='git commit --amend --no-edit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias glog='git log --oneline --decorate --graph'
alias gpull='git pull'
alias gpush='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias gfpush='gpush --force'
alias gss='git status'

alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'

alias mpc='mpc -h /run/user/$UID/mpd.sock'
alias vi='nvim'
alias vim='nvim'
alias vimb='nvim ~/.bashrc'
alias vimc='nvim ~/.dotfiles/terminal/neovim/init.vim'

alias s='source ~/.bashrc'

alias xcopy='xclip -selection clipboard'
alias xpaste='xclip -selection clipboard -o'

# vim:ft=sh
